### ISSUE TITLE
TLS support for endpoint? 

### ISSUE THREAD

**Issue by x-magic** [memobird/gugu-php#3]
Happy to join the developer program but just realised that endpoints mentioned in docs doesn't support secure connection over default port 443. 

```
$ curl -v https://open.memobird.cn/home/setuserbind
* timeout on name lookup is not supported
*   Trying 139.219.228.164...
* connect to 139.219.228.164 port 443 failed: Timed out
* Failed to connect to open.memobird.cn port 443: Timed out
* Closing connection 0
curl: (7) Failed to connect to open.memobird.cn port 443: Timed out
```

Is there a separate secure endpoint or current API is not secured? For the latter, is there a plan to implement secure connection? 

Cheers

**Comment by DNLi303** [comment]
hi, understand the open docs was wrong
we are support the http api  don't  https ,
so the connection url is http://open.memobird.cn
i am the official developer of memobird,
welcome join the developer program, i will support the help for you

**Comment by x-magic** [comment]
I've got requests working already. I'm just suggesting that implementing TLS would be a good idea. It's more secure, after all. 

Cheers
